const List<Map<String, dynamic>> fruits = [
  {
    'name': 'Lime',
    'squareImage': 'lime.jpg',
    'bannerImage': 'limes.jpg',
    'healthInfo': '9 calories',
    'family': 'Citrus',
    'numLikes': 7,
    'numDislikes': 2,
    'isLiked': true,
    'tastiness': 4,
  },
  {
    'name': 'Tomato',
    'squareImage': 'tomato.jpg',
    'bannerImage': 'tomatoes.jpg',
    'healthInfo': '12 calories',
    'family': 'Nightshade',
    'numLikes': 10,
    'numDislikes': 3,
    'isLiked': true,
    'tastiness': 4,
  },
  {
    'name': 'Kiwi',
    'squareImage': 'kiwi.jpg',
    'bannerImage': 'kiwis.jpg',
    'healthInfo': '20 calories',
    'family': 'Actinidiaceae',
    'numLikes': 5,
    'numDislikes': 6,
    'isDisliked': true,
    'tastiness': 3,
  },
  {
    'name': 'Lemon',
    'squareImage': 'lemon.jpg',
    'bannerImage': 'lemons.jpg',
    'healthInfo': '5 calories',
    'family': 'Citrus',
    'numLikes': 12,
    'numDislikes': 11,
    'tastiness': 2,
  },
  {
    'name': 'Orange',
    'squareImage': 'orange.jpg',
    'bannerImage': 'oranges.jpg',
    'healthInfo': '30 calories',
    'family': 'Citrus',
    'numLikes': 10,
    'numDislikes': 1,
    'tastiness': 5,
  },
  {
    'name': 'Strawberry',
    'squareImage': 'strawberry.jpg',
    'bannerImage': 'strawberries.jpg',
    'healthInfo': '11 calories',
    'family': 'Berry',
    'numLikes': 21,
    'numDislikes': 1,
    'isLiked': true,
    'tastiness': 5,
  },
  {
    'name': 'Avocado',
    'squareImage': 'avocado.jpg',
    'bannerImage': 'avocados.jpg',
    'healthInfo': '30 calories',
    'family': 'Guacamole ingredients',
    'numLikes': 12,
    'numDislikes': 4,
    'tastiness': 4,
  },
];
